Feat #30개인준비물을위한entity구성
TravelRole/roleTravel-backend pull request #31
Opened 2023-04-10 12:51 UTC by Icln

개인 준비물을 담을 Entity를 구현했습니다.

2023-04-10 13:44 UTC, guswls159357 commented
현재 master 브랜치로 PR 되어있는데, dev 브랜치로 하셔야 할 것 같습니다!

2023-04-10 13:52 UTC, kwYoohae requested changes
코드작성 수고하셨습니다!!! 작은 단위로 브랜치를 잡은것이 좋은 것 같아요!!

다음에는 해당하는 로직을 짜는것도 좋고, 다른 부분을 짜는것도 좋습니다!!!
못정하겠으면, 말씀해주시면 구현로직을 추천해드리도록 하겠습니다

Notion task에서 일정관리 부탁드립니다!!

2023-04-10 13:52 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/domain/Preparation.java
> +@Table(name = "PREPARATION")
ERD 상에서는 `travel_essentials`이라고 명명되어있습니다!!

다시 한번 확인해주세요!!
<img width="647" alt="image" src="https://user-images.githubusercontent.com/74089271/230913729-17fb4895-a00f-4bba-a56b-5539e58e49db.png">

2023-04-10 13:52 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/user/domain/User.java
>  	public void updateRefreshToken(final String refreshToken) {
띄어쓰기가 있으면 좀 더 좋을것 같아요!!

2023-04-10 13:52 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/domain/Preparation.java
> +    private String item;
nit: 의미명대로 `itemName`으로 하는것도 좋아보여요!!

2023-04-10 13:53 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/domain/Preparation.java
> +    private Boolean check;
해당변수도 그냥 `check보다는 `isChecked`로 Boolean 변수 명명법을 따르는게 좋을것 같아요!!

2023-04-10 14:56 UTC, Icln commented on src/main/java/com/travel/role/domain/room/domain/Preparation.java
> +@Table(name = "PREPARATION")
확인했습니다!

2023-04-10 14:56 UTC, Icln commented on src/main/java/com/travel/role/domain/user/domain/User.java
>  	public void updateRefreshToken(final String refreshToken) {
수정했습니다!

2023-04-10 14:56 UTC, Icln commented on src/main/java/com/travel/role/domain/room/domain/Preparation.java
> +    private String item;
수정했습니다!

2023-04-10 14:56 UTC, Icln commented on src/main/java/com/travel/role/domain/room/domain/Preparation.java
> +    private Boolean check;
수정했습니다 리뷰 감사합니다!

2023-04-10 15:20 UTC, guswls159357 commented on src/main/java/com/travel/role/domain/room/domain/TravelEssentials.java
@JoinColumn 에도 nullable, updatable 등 추가적인 설정을 해주면 좋을 것 같습니다!
또한 AllArgsConstructor, NoArgsConstructor, Builder 등 객체를 생성할 수 있는 방법이 많은데,
이 것들을 모두 사용해야 하는지, 사용해야 한다면 접근제어자는 public 이 적당한 지 등을 고려해본다면 더욱 좋을 것 같습니다!

2023-04-11 04:33 UTC, Icln commented on src/main/java/com/travel/role/domain/room/domain/TravelEssentials.java
nullable 옵션 추가했습니다. 리뷰 감사드립니다!!
아래 내용에 대해서는 더 공부해보도록 하겠습니다 감사합니다!

2023-04-11 05:02 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/domain/TravelEssentials.java
@guswls159357 
` @joincolumn`에 대한 언급처럼 `@` 가 들어가는 항목을 언급하게 된다면, 다음과 같이 모르는 사람이 언급이 되어버립니다!!

그래서 백틱을 붙이면 좀더 좋을것 같습니다 `요로코롬` 입니다!!
<img width="497" alt="image" src="https://user-images.githubusercontent.com/74089271/231060801-421be84a-a09d-4ef9-ad34-a43ed0fe4080.png">

2023-04-11 07:20 UTC, kwYoohae approved these changes
LGTM👍

2023-04-11 07:20 UTC, merged