Feat #59가고싶은장소삭제api
TravelRole/roleTravel-backend pull request #63
Opened 2023-04-17 13:08 UTC by Icln

- roomId와 placeId를 인자로 넘겨주었을 때 가고싶은 장소 삭제하는 기능 구현

2023-04-17 14:43 UTC, kwYoohae requested changes
코드작성 고생 많으셨습니다 :)

2023-04-17 14:43 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/controller/WantPlaceController.java
> +    @ResponseStatus(HttpStatus.OK)
`OK`는 Default값이라 안넣어도 될것 같습니다!!

2023-04-17 14:43 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
> +        checkParticipant(loginUser, room.getRoomParticipants());
생각해보니까 `chekParticipant` 정도는 Spring Data JPA의 `existsBy`를 통해서 포문을 굳이 안돌더라도 해결할 수 있지 않을까요?

2023-04-17 14:43 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
> +    private WantPlace checkPlaceId(Long placeId){
확인하는것이 반환하는거니 `checkPlaceId` 보다는, `findPlaceId`가 더 맞을것 같습니다. 

또한, `check`만 하고싶다면, boolean을 사용하는것도 나쁘지 않을까 싶습니다 번복해서 죄송합니다 😢

2023-04-17 14:43 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
> +    }
`delete`를 하기전에 굳이 check할 필요가 있을까요?

2023-04-17 15:21 UTC, Icln commented on src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
> +    }
넘겨준 placeId가 존재하지 않을 때를 예외처리 하기 위해서 checkPlaceId를 사용했습니다.
만약 해당 pk 값의 데이터가 존재하는지 확인을 하고 없으면 예외를 발생시킵니다. 
또한 넘겨준 placeId를 통해 가고싶은 장소에 대한 정보를 얻어오면 이를 삭제하기 위해서 이렇게 작성했습니다

2023-04-17 15:37 UTC, Icln commented on src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
> +    }
생각해보니까 try catch 문을 사용하면 check를 사용하지 않아도 되겠네요!

2023-04-17 16:36 UTC, Icln commented on src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
> +        checkParticipant(loginUser, room.getRoomParticipants());
해당 방법에 대해서 찾아봤는데 이해가 잘 안가서 설명해주시면 감사하겠습니다!

2023-04-17 16:38 UTC, guswls159357 commented on src/main/java/com/travel/role/domain/user/exception/PlaceInfoNotFoundException.java
> +    public PlaceInfoNotFoundException(String msg) {super(msg);}
생각해보니, 해당 Exception 의 메시지는 단 하나만 반환하게 되어, super(msg) 부분을 super(ExceptionMessage.PLACE_NOT_FOUND) 로 변경하고, 생성자의 인자를 받지 않아도 될 것 같습니다!!

2023-04-18 04:53 UTC, Icln commented on src/main/java/com/travel/role/domain/user/exception/PlaceInfoNotFoundException.java
> +    public PlaceInfoNotFoundException(String msg) {super(msg);}
의견 감사합니다!! 반영했습니다!

2023-04-18 05:01 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
> +        checkParticipant(loginUser, room.getRoomParticipants());
`DB`에서 이를 처리하게 일임하는것도 나빠보이지 않는다는 소리였습니다 !!

2023-04-18 05:12 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/service/WantPlaceService.java
> +    }
제가 하고 싶은말은 다음과 같습니다 !!
`deleteById`는 사실상 로직을 확인하면, 다음과 같이 구성이 되어있습니다
<img width="739" alt="image" src="https://user-images.githubusercontent.com/74089271/232676415-cd997b1e-dfcb-4bb7-bbed-73af146f59f2.png">

결국 `findById`로 값을 가져와서 `delete`를 한다는 소리입니다. 

만약, PK값이 없다면, 자동적으로 Exception이 나오게 됩니다.
그래서, 굳이, 앞서서 `deleteById`를 사용할 필요는 없다고 생각했던것 입니다!!

만약, 이렇게 구성하게 된다면, findById로 찾고, deleteById를 호출하고 findById로 호출해서 찾고, delete를 실행하는것과 같다고 느껴졌습니다!!

음... 애초에 `findById`로 먼저 찾았을경우, 영속성 컨텍스트에 존재하기때문에, 쿼리문이 따로 더 나가지는 않을것 같지만 불필요한 로직이라고 생각을했습니다. 또한, 이미 해당하는 Exception이 존재하기 때문에 다음을 사용하는것도 나쁘지 않아보입니다!!

2023-04-18 06:02 UTC, kwYoohae approved these changes
이후에 검증 로직은 한번 성능테스트 하면 좋을것 같아요 

코드작성 고생많으셨습니다 :)

2023-04-18 06:41 UTC, merged