Feat #62 room invite code
TravelRole/roleTravel-backend pull request #64
Opened 2023-04-17 14:25 UTC by kwYoohae

### 구현 내용
- 초대코드를 받는 로직을 작성함
- 만약, 하루가 지난다면, 초대코드가 유효하지 않도록하고, 다시 초대링크 복사를 할때는, 새로운 랜덤 20글자의 값이 반환이됨
### 테스트 코드
<img width="679" alt="image" src="https://user-images.githubusercontent.com/74089271/232515705-39ddd187-a9e0-460d-8569-b7db419fc808.png">

### 이후 목표
- 인수테스트 부분에서, id값이 계속 변경함, sql로 인수테스트에 사용할 데이터들을 넣는 작업을 변경할 예정

2023-04-17 16:41 UTC, guswls159357 commented on src/main/java/com/travel/role/domain/room/controller/RoomController.java
> +@RequestMapping("/api/")
해당 부분에 / 를 추가하신 이유가 있을까요??

2023-04-17 16:55 UTC, guswls159357 commented on src/main/java/com/travel/role/domain/room/domain/Room.java
> +	private LocalDateTime roomInviteTime;
혹시 이 시간이 초대 만료시간이 맞나요?? 맞다면 expireTime 등으로 변경하는게 더 가독성이 좋을 것 같습니다!!

2023-04-17 16:58 UTC, guswls159357 commented on src/main/java/com/travel/role/domain/room/exception/UserHaveNotPrivilegeException.java
> +	public UserHaveNotPrivilegeException(String msg) {super(msg);}
해당 Exception 의 메시지가 단 하나의 메시지(ExceptionMessage 내에 존재하는) 만 사용한다면 아예 
생성자에서 파라미터를 받지 않고, 내부에서 super(USER_HAVE_NOT_PRIVILEGE) 로 사용해도 좋을 것 같습니다!!

2023-04-17 17:08 UTC, guswls159357 commented on src/test/java/com/travel/role/domain/room/RoomTest.java
해당 테스트에서, beforeEach 를 사용하셨는데, 각 메서드마다 반드시 초기화 되어야 하는 것이 아니라면, 
BeforeAll 을 사용하는 것도 좋을 것 같습니다!

2023-04-18 03:24 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/controller/RoomController.java
> +@RequestMapping("/api/")
앗 오타... 같네요 ㅠㅠㅠ

2023-04-18 03:24 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/domain/Room.java
> +	private LocalDateTime roomInviteTime;
그게더 가독성 있어보이네요 확인했습니다 :)

2023-04-18 03:25 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/exception/UserHaveNotPrivilegeException.java
> +	public UserHaveNotPrivilegeException(String msg) {super(msg);}
강제적이면, 사실 생성자가 필요없긴 하네요 좋은의견인것 같습니다!!

2023-04-18 03:25 UTC, kwYoohae commented on src/test/java/com/travel/role/domain/room/RoomTest.java
`BeforeAll`은 static이라서 빈주입받기가 어려워서 건들지 못했네요... 

해당 내용을 해결하신 적이 있으실까요? @guswls159357

2023-04-18 06:03 UTC, guswls159357 commented on src/test/java/com/travel/role/domain/room/RoomTest.java
https://velog.io/@joosing/JUnit-BeforeAll-non-static%EC%9C%BC%EB%A1%9C-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0

저는 다음과 같은 방법으로 설정하여 구현했습니다!!

2023-04-18 06:41 UTC, Icln requested changes
코드 작성하느라 고생하셨습니다!

2023-04-18 06:41 UTC, Icln commented on src/main/java/com/travel/role/domain/room/controller/RoomController.java
> +	public String getInviteCode(@AuthenticationPrincipal UserPrincipal userPrincipal, Long roomId) {
프론트에서 roomId라는 이름으로 요청을 하기 때문에 `@RequestParam을 붙이지 않으신 것인지 궁금합니다!!

2023-04-18 06:41 UTC, Icln commented on src/main/java/com/travel/role/domain/room/domain/Room.java
> +	private LocalDateTime roomExpiredTime;
앞에 room이 붙어 방에 만료 시간이 있는 것인지 헷갈릴 수 있다고 생각합니다!!
room을 code로 바꾸면 가독성이 좋아질 것 같습니다!

2023-04-18 06:41 UTC, Icln commented on src/main/java/com/travel/role/domain/room/service/RoomService.java
> +		List<RoomRole> roomRoles = roomRepository.getRoomRole(userPrincipal.getEmail(), roomId);
제가 이해하기로는 ADMIN 권한이 있는 참여자만 초대 코드를 만들 수 있는 메소드인 것 같습니다.
이때 Role을 판단하기 위해서 하셨는데 추천해주신 exisitsBy를 사용하면 validRoomRole에서 반복문을 사용하지 않아도 될 것 같습니다!

2023-04-18 06:41 UTC, Icln commented on src/main/java/com/travel/role/domain/room/service/RoomService.java
> +	private void validRoomRole(List<RoomRole> roomRoles, RoomRole... checkRooms) {
...을 사용하신 이유가 후에 초대 코드를 만들 수 있는 역할이 늘어날 수 도 있는 것을 대비하신 건가요??

2023-04-18 13:29 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/controller/RoomController.java
> +	public String getInviteCode(@AuthenticationPrincipal UserPrincipal userPrincipal, Long roomId) {
생각해보니 방이름을 `@RequestParam`으로 받는게 훨씬 좋겠네요 감사합니다 !!

2023-04-18 13:30 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/service/RoomService.java
> +	private void validRoomRole(List<RoomRole> roomRoles, RoomRole... checkRooms) {
공통으로 사용되는 메서드로 만들고 싶어서 가변인자를 사용했습니다!!

2023-04-24 11:41 UTC, Icln approved these changes
LGTM

2023-04-24 11:56 UTC, Icln approved these changes

2023-04-24 11:56 UTC, Icln commented on src/main/java/com/travel/role/global/auth/service/AuthService.java
> +		String randomPassword = passwordGenerator.generateRandomPassword(16);
20글자의 값이 반환이 된다고 설명이 되어있는데 16으로 바뀌어서 오류인지 아니면 일부러 바꾸신 건지 명시해주시면 좋을 것 같습니다!

2023-04-24 11:56 UTC, merged