feat: 방 정보 입력 및 생성, 방 리스트 조회
TravelRole/roleTravel-backend pull request #8
Opened 2023-03-27 13:17 UTC by cw-y

### 구현목록
* 방 항목 생성 요청 구현
* 모든 방 리스트 조회

2023-03-28 02:18 UTC, kwYoohae requested changes
나머지는 공통사항인것 같습니다. 

1. Table의 컬럼명을 ERD와 동일하게 매핑해주셨으면 좋겠습니다
2. 프로젝트 구조가 잘못된것 같습니다. `global`은 글로벌하게 사용하는것만 넣는곳이지 `Room` 즉, 도메인에 관련한 것들이 담기는곳이 아닙니다.
3. 테스트 코드가 따로 없어서 제대로 동작하는지 확인하기가 어렵습니다 테스트 코드를 사용해서 코드를 검증하는 로직을 넣는방법도 좋고, 따로 Postman으로 확인한 결과를 보고싶습니다!!
4. 컬럼에 각각의 length도 직접적으로 명시해서 넣는것이 좋을것 같습니다
5. 빈칸도 코드컨벤션의 한가지입니다 의미없는 빈칸은 없는것이 좋을것 같습니다!!
6. 주석도 좋지만, 주석을 안써도 이해할 수 있도록 코드를 짜는것이 좋다고 생각합니다

코드작성 고생많으셨습니다!!

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/dao/RoomRepository.java
> +public interface RoomRepository extends JpaRepository<RoomEntity, String> {
`String` 타입을 쓰는것이 아닌것 같습니다 다음 값은 아이디 값의 타입이 들어와야하는것으로 알고 있습니다.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/74089271/228108424-87ce9438-4fa4-4ca8-8772-18087a4114e6.png">

2023-03-28 02:18 UTC, kwYoohae commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
`lombok`이 적용이 잘되는데 따로 `annotationProcessor`로 추가하신 이유가 있나요?

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/domain/RoomEntity.java
> +    private LocalDateTime createdAt;
`Auditing` 기능을 사용하기에는 안에있는 `BaseTime`처럼 상속을 받는 형식이 좀더 좋을것 같습니다

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/domain/RoomEntity.java
> +@Table(name = "roomInfo")
ERD를 보시면 `ROOM_INFO`로 명시가 되어있습니다!!

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/controller/RoomInfoController.java
> +@RequestMapping("/roomInfo")
`roomInfo`말고 다른 api도 많이 들어오지 않을까요? 

또한, api는 구분자는 `-`로 구분하는것이 좀더 좋습니다

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/controller/RoomInfoController.java
> +    private RoomInfoService service;
`Autowired`보다는 생성자 주입이 훨신 좋습니다

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/controller/RoomInfoController.java
> +        }
Exception을 처리할때는 `@RestControllerAdvice`를 사용하는것이 좀더 좋을것 같습니다

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/dto/RoomInfoDTO.java
> +    }
이를 정적 팩토리 메서드로 바꾸는것이 좀더 좋은것 같습니다

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/service/RoomInfoService.java
> +    private RoomRepository repository;
이 또한 생성자 주입이 좀더 좋은것 같습니다

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/service/RoomInfoService.java
> +    public void validate(final RoomEntity entity){
굳이 `public`일 필요는 없는것 같습니다

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/service/RoomInfoService.java
> +            throw new RuntimeException("Entity cannot be null.");
따로 CustomException이 있으면 좋을것 같습니다 또한, 값도 하드코딩보다는 상수를 사용하는것이 좋다고 느껴집니다

2023-03-28 02:18 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/service/RoomInfoService.java
> +        repository.save(entity);
분명 메서드명은 `validate`인데 `save` 로직이 있다는 것은 옳지 않다고 생각됩ㄴ디ㅏ

2023-03-28 11:52 UTC, kwYoohae commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
저도 새로 clone해서 확인해보니 같은오류가 발생하네요... 왜 제 인텔리제이에서는 딱히 설정을 안했는데 돌아가는지 모르겠네요

확인했습니다 :) annotationProcessor를 사용할때, 원래 사용하고 있는 버전을 명시하는것이 좀 더 좋을 것 같습니다!!

2023-03-28 13:16 UTC, cw-y commented on src/main/java/com/travel/role/global/auth/service/RoomInfoService.java
> +            throw new RuntimeException("Entity cannot be null.");
에러메시지 클래스를 따로 생성해야 할까요?

2023-03-28 13:20 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/service/RoomInfoService.java
> +            throw new RuntimeException("Entity cannot be null.");
커스텀 Exception을 사용하는것도 좋고, 상황에 맞는 Exception을 사용하는것이 좋을것 같습니다. 

`RuntimeExcpetion`은 사실상 Runtime환경에서 아예프로그램을 종료하지 않는다는 성격만 나타내기때문에 `IllegalArgumentException`같은 이미 만들어진 상황에 맞는 빌트인 Exception을 쓰는것도 좋다고 생각합니다.

또한, `@RestControllerAdvice`를 공부하시면서 확인한번해보시고 좀더 좋다고 생각하는것을 쓰는것이 좋을것 같습니다!

2023-03-28 14:03 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/controller/RoomInfoController.java
> +@RequestMapping("/roomInfo")
`roomInfo`를 쓰시고 싶으면 `room-info` 가 더 나을것 같습니다

명명법에 대해서 공부하시고 좀 더 좋으신걸로 찾아서 쓰시는게 좋을것 같습니다

2023-03-28 14:54 UTC, cw-y commented on src/main/java/com/travel/role/global/auth/controller/RoomInfoController.java
> +@RequestMapping("/roomInfo")
아하넵넵 알겠습니다! 근데 혹시 roomInfo 말고 다른 api도 들어온다고 하신건 어떤 api가 있을지 여쭤봐도 될까요?

2023-03-28 22:50 UTC, kwYoohae commented on src/main/java/com/travel/role/global/auth/controller/RoomInfoController.java
> +@RequestMapping("/roomInfo")
이 Controller안에서 Room entity를 조작하는 여러가지 api가 생기지않을까요???

지금만든는 방을 만드는 로직뿐만이아니라. 방조회도 등등 여러가지가 생길 수도 있다는 말 이었습니다

2023-04-01 13:05 UTC, kwYoohae requested changes
리뷰 수정 감사드립니다 공통적으로 이야기할 부분이 있어서 다시 이야기 드립니다!!

1. `ResponseDTO`는 공통적으로 사용하는 변수인것 같습니다. 그래서 `global`로 옮기는게 좀더 나아 보입니다. 
2. Conflict가 해결되지 않은것 같습니다. 다시한번 확인바랍니다. 
3. Transcation을 적용하고 읽기만 하는 부분은 `readOnly` 옵션을 하는것이 좋을것 같습니다.
4. 테스트 코드 및, 테스트 결과를 확인하는 부분이 필요하다고 했는데 까먹으신것 같습니다. 그 부분도 올려주시면 좋을것 같습니다!!

2023-04-01 13:05 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/service/RoomInfoService.java
> +    }
메서드 이름은 `create`인데 왜 `findAll()`로 모든 변수들을 반환할까요? 
메서드는 한가지 일만 하는것이 좋은것 같습니다!!!

2023-04-01 13:05 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/service/RoomInfoService.java
> +        validate(entity);
로직을 확인했을때 Controller에서 dto받기 -> Entity 만들기 -> create 하기로 보이는데
굳이 `validate`에 대해 확인할때, `null`을 여기서 확인하는 이유가 명확히 보이지 않습니다

`null` check를 하고 싶으면 dto단에서 먼저 확인 하는것이 좋을것 같습니다. validate 기능을 해주는 어노테이션이 따로 있으니 따로 찾아보는 것이 좋을 것 같습니다.

2023-04-02 09:46 UTC, cw-y commented on src/main/java/com/travel/role/global/exception/ExceptionFilterResponse.java
> +}
pull 했더니 두개다 생겼습니당...

2023-04-03 01:32 UTC, kwYoohae commented on src/main/java/com/travel/role/global/exception/ExceptionFilterResponse.java
> +}
그러면 pull하고 존재했던것을 사용 또는 다른것을 사용하는것이 좋을것 같습니다. 

중복되는 것은 하나로 통일하는게 좀더 좋을것 같습니다. 이따가 같이 뭐가 중복되는지 확인하면 좋을것 같습니다!!

2023-04-03 03:45 UTC, kwYoohae requested changes
코드 작성 수고하셨습니다!! 

이번에는 테스트 코드를 작성하셨더라구요 잘하신것 같습니다 :) 

말씀드릴점은 다음과 같습니다. 
1. `Controller`단 테스트와 기존 서비스 테스트는 다른 Class로 분리하는것이 좀더 좋을 것 같습니다
2. API 명명법을 한번 더 확인하시는 것이 좋을것 같습니다. `create` 나 `read`를 붙이는것은 안좋은것 같습니다
3. `@Transactional`의 사용법이 잘못된 것 같습니다. 다시한번 확인해보시면 좋을것 같습니다. `Controller`단에 붙이는건 아니라고 생각합니다. 
4. 아직 `Controller`단에서 로직이 너무 많이 보이는것 같습니다. Layered Architecture에 대해서 공부를 좀더 하시는것이 좋을것 같습니다.

2023-04-03 03:45 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/controller/RoomInfoController.java
> +//@RequestMapping("/")
주석은 제거해주세요!!

2023-04-03 03:45 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/controller/RoomInfoController.java
> +    public ResponseEntity<?> createRoom(@RequestBody RoomInfoDTO dto) {
`?` 보다는 확실한 타입을 입력해주시는게 좀 더 좋은것 같습니다!!

2023-04-03 03:45 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/controller/RoomInfoController.java
> +            LocalDateTime ED = dto.getTravelEndDate();
`SD` `ED` 보다는 길어도 확실한 명명을 해주는게 좋은것 같스빈다!!

2023-04-03 03:45 UTC, kwYoohae commented on src/main/java/com/travel/role/global/exception/ExceptionFilterResponse.java
> +    private String time;
빈 엔터를 치신것 같습니다!!

2023-04-03 03:45 UTC, kwYoohae commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
제대로 Pull 이후에 Conflict 해결을 안하신것 같네요!! 주석도 지워주시길 바랍니다

2023-04-03 03:45 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/room/exception/RoomExceptionMessage.java
> +}
nit: `RoomExceptionMessage` 보다는 한가지의 Class로 묶는게 좋은것 같습니다. 제 개인적인 생각이라 무시하고 진행해주셔도 상관 없을것 같습니다

2023-04-04 11:45 UTC, kwYoohae commented
공부를 하다가 좋은 글을 발견해서 남깁니다!!
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/74089271/229781551-5c82130e-bfe2-47fc-8e75-089b6c0e1de4.png">

다음처럼, 복잡성이 증가할 수도 있기 때문에 하나의 GlobalExceptionHandler에서 Exception을 처리하면 좋을것 같아요!!

이전 `RoomExceptionHandler`보다는 `global` 패키지에 있는 `ExceptionHandler`로 옮기면 좀 더 좋을것 같습니다!!!

2023-04-06 13:47 UTC, kwYoohae commented
Entity를 생성하면서 다시 확인하고있는데, 불필요한 코드가 다시보여 연락드렸습니다. 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/74089271/230396984-f7c9ec9a-97cb-4953-aaec-05b048a061b2.png">
다음 그림에는 Entity임에도 불구하고 `@NotNull`, `@NotBlank`, `@Size` 등 Validation 기능을 넣었는데, 이는 Entity 시점에서 Validate를 확인하기 보단, Controller 단에서 확인하는것이 좀더 낫다고 판단됩니다.

2023-04-08 05:57 UTC, closed without merging