Feat #54가고싶은장소일정에추가하는api작성
TravelRole/roleTravel-backend pull request #90
Opened 2023-04-29 13:31 UTC by Icln

### 구현 목록
- 찜목록에서 일정에 추가하는 API 작성

### 테스트 코드 결과
![image](https://user-images.githubusercontent.com/55732952/235305577-dd855f71-7d2b-4317-a11c-9f1521ec03f5.png)

2023-04-30 03:20 UTC, kwYoohae requested changes
코드작성 고생많으셨습니다. 

`commit` 내용에서 `delete`를 사용하고 싶다면, `fix`나, `refactor`, 'chore' 같은 경우가 더 좋을것 같습니다!!

2023-04-30 03:20 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/board/controller/BoardController.java
> +    }
201이 좀더 좋은 결과일것 같습니다 :)

2023-04-30 03:20 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/board/entity/Board.java
> +
`OneToOne`으로 하신것 같은데 다음처럼 1:N으로 되어있는것같네요??? 
저만 그러는거일수도 있으니까 확인한번 부탁드립니다
<img width="506" alt="image" src="https://user-images.githubusercontent.com/74089271/235333614-25dca217-f5dc-43f0-9080-a5b9971e843e.png">

2023-04-30 03:20 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/board/entity/Board.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "Asia/Seoul")
여기에 `JsonFormat`을 한 이유는 무엇일까요? Entity를 Request혹은 Response로 사용하는것은 위험할것같습니다!!

2023-04-30 03:20 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/board/entity/BookBoard.java
> +    private BigDecimal price;
혹시 우리 해외도 하는것으로 하기로 했었나요? 잠시 이야기 나눴을때 그랬던것같은데
한번확인 부탁드립니다 만약, 해외가 없으면 그냥 값을 가져가도 무관할것 같습니다!!

2023-04-30 03:20 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/board/service/BoardService.java
> +    }
이 과정을 `boardRequestDTO`에서 팩터리 메서드로 Entity로 변경하게 하면 좀더 깔끔하게 값을 얻고 save를 따로 함수로 안만들어도 좋을것 같습니다

2023-04-30 03:20 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/board/service/BoardService.java
> +        addBookBoard(board, boardRequestDTO);
띄어쓰기로 각 로직을 분리하면 좀더 코드가 깔끔하게 보일것 같습니다!!

2023-04-30 03:20 UTC, kwYoohae commented on src/test/java/com/travel/role/unit/room/service/BoardServiceTest.java
> +    }
추가성공 로직을 그냥 time으로 확인하는거는 굳이 테스트코드가 필요없을것 같습니다

확인을 하고 싶다면 이를 통합테스트로 옮기는것이 좀더 나아보입니다

save는 굳이 예외사항을 테스트하는것이 아니면 다른 테스트에서 확인하는것이 좋을것 같습니다

2023-04-30 03:20 UTC, kwYoohae commented on src/test/java/com/travel/role/unit/room/service/BoardServiceTest.java
> +    }
만약 사용하신다면, 새로 인스턴스를 생성하는 메서드이기 때문에 `get`보다는 `create`, `make`, `generate`가 더 어울리는것 같습니다

2023-04-30 13:57 UTC, Icln commented on src/main/java/com/travel/role/domain/board/entity/Board.java
> +
확인해보겠습니다!!

2023-04-30 13:58 UTC, Icln commented on src/main/java/com/travel/role/domain/board/entity/Board.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "Asia/Seoul")
수정하겠습니다!!

2023-05-01 03:20 UTC, Icln commented on src/main/java/com/travel/role/domain/board/entity/Board.java
> +
확인을 해봤는데 매핑 자체에는 문제 없는 것 같습니다. 하지만 ERD 표기상의 오류가 발생해서 1:N 관계로 표시되는 것 같습니다.

2023-05-01 03:20 UTC, kwYoohae commented on src/main/java/com/travel/role/domain/board/entity/Board.java
> +
확인해주셔서 감사드립니다 :)

2023-05-01 03:33 UTC, kwYoohae approved these changes
LGTM👍

2023-05-01 03:33 UTC, merged